export const content = {
  en: {
    langLabel: "EN",
    nav: {
      home: "Home",
      cruises: "Cruises",
      piers: "Departure piers",
      practicalInfo: "Practical info",
      event: "Event on cruise",
      about: "About us",
      community: "Community reviews",
    },
    hero: {
      title: "Bangkok River Cruise Guide",
      subtitle: "Indulge in an unforgettable luxury journey through the heart of Bangkok's historic waterway, where tradition meets modern elegance.",
    },
    landmarks: {
      title: "Chao Phraya River route and landmarks",
      subtitle: "The Chao Phraya River is the lifeblood of Bangkok, flowing through the historic Rattanakosin old town where temples, palaces, and major attractions",
      landmark: "ICONSIAM",
      description: "The atmosphere is especially impressive in the evening, when the lights from the buildings and passing cruises reflect beautifully on the Chao Phraya River.  Inside, visitors can enjoy a lively mix of shopping, dining, and relaxation in a setting that feels both elegant and energetic.",
      cta: "Explore more",
      items: [
        {
          key: "iconsiam",
          title: "ICONSIAM",
          description: "The atmosphere is especially impressive in the evening, when the lights from the buildings and passing cruises reflect beautifully on the Chao Phraya River. Inside, visitors can enjoy a lively mix of shopping, dining, and relaxation in a setting that feels both elegant and energetic.",
        },
        {
          key: "rama8",
          title: "Rama VIII Bridge",
          description: "It is one of the world's longest asymmetrical cable-stayed bridges, spanning the Chao Phraya River to connect the Phra Nakhon and Thonburi sides. It is distinguished by its single, inverted Y-shaped bridge pier, exquisitely designed to honor His Majesty King Bhumibol Adulyadej (Rama VIII) and to help alleviate traffic congestion.",
        },
        {
          key: "grandPalace",
          title: "The Grand Palace",
          description: "One of Bangkok's most iconic landmarks and the former royal residence of Thai kings since 1782. Its grand Thai architecture and historic atmosphere make it a must-see highlight along the Chao Phraya River.",
        },
        {
          key: "watArun",
          title: "Wat Arun",
          description: "Also known as the Temple of Dawn, Wat Arun is one of Bangkok's most beautiful riverside temples. Its iconic central prang stands gracefully beside the Chao Phraya River, offering a stunning view especially at sunset and at night.",
        },
      ],
    },
    operators: {
      title: "All cruise operators",
      seeAll: "See all",
      categories: ["All cruise", "Dinner cruise", "Sunset cruise", "Modern Luxury cruise", "Thai Classic Luxury Cruise", "Romantic Dining Cruise"],
      labels: { price: "PRICE", decks: "DECKS", levels: "2 Levels", dinner: "Dinner cruise", rating: "4.7 (1,503 reviews)", foods: ["Buffet", "Fusion set", "Thai set"], cta: "View details" },
      cards: [
        { title: "VELA Cruise", price: "฿699-1,600", category: "dinner" },
        { title: "Riverside Faraya Cruise", price: "฿699-1,600", category: "dinner" },
        { title: "White Orchid River Cruise", price: "฿899-1,600", category: "dinner" },
        { title: "Unicorn Cruise", price: "฿1,690-2,200", category: "modern" },
        { title: "Viva Alangka Cruise", price: "฿1,300-1,900", category: "sunset" },
        { title: "Meridian Cruise", price: "฿1,400-2,000", category: "classic" },
        { title: "Royal Romantic Dining", price: "฿1,890-2,500", category: "romantic" },
      ],
    },
    culinary: {
      title: "Culinary excellence above the water",
      subtitle: "Our world-class chefs bridge the gap between tradition and innovation. Enjoy a curated selection of authentic Thai flavors and international favorites, prepared with the freshest local ingredients.",
      items: [
        ["Vegetarian option available", "Premium vegetarian selections, thoughtfully prepared for every guest."],
        ["Halal Certified Ingredients", "Halal-certified ingredients for a refined and worry-free dining experience."],
        ["Gluten free option available", "Gluten-free options prepared with care and attention."],
        ["Indian dinner buffet cruise", "Authentic Indian buffet dining on an elegant river cruise."],
      ],
    },
    piers: {
      title: "Departure piers",
      seeAll: "See all",
      hours: "Daily operating hours: 06:00-23:00",
      cards: ["ICONSIAM Pier", "River City Pier", "Asiatique Pier", "Tha Maharaj Pier", "Sathorn Pier", "Yodpiman Pier", "Terminal 21 Rama 3 Pier", "Wat Arun Pier"],
      submenu: ["ICONSIAM Pier", "River City Pier", "Asiatique the Riverfront Pier"],
    },
    blogs: {
      title: "Real experience blogs",
      subtitle: "Discover stories from travelers who have experienced our river cruises",
      seeAll: "See all",
      readMore: "READ MORE...",
      date: "01 Jan 2026",
      cards: Array.from({ length: 5 }, () => ({
        title: "A unique experience! Delicious food",
        description: "A unique experience! Delicious food, very friendly staff, very well organised, in a romantic atmosphere, with possibility and time to enjoy the beautiful landmarks of Bangkok, seen from the river.",
        author: "C********",
        date: "01 Jan 2026",
        cruise: "The luxury White Orchid Cruise",
        imageCount: "+3",
      })),
    },
    reviews: {
      title: "Reviews",
      subtitle: "Authentic reviews from our verified guests",
      seeAll: "See all",
      verified: "From verified users",
      date: "01 Jan 2026",
      readMore: "READ MORE...",
      cards: ["Eleanor Thompson", "Marcus Chen", "Sarah Jenkins", "Marcus Chen", "Sarah Jenkins"].map((name) => ({
        name,
        description: "The service was impeccable. Watching the sunset over Wat Arun from the top deck with a glass of champagne is a memory I will cherish forever.",
        imageCount: "+99",
        verified: "From verified users",
        date: "01 Jan 2026",
      })),
    },
    seo: {
      title: "Discover the Best Luxury River Cruises in Bangkok",
      paragraphs: [
        "A Chao Phraya River cruise is more than just a boat ride; it is a gateway into the heart and soul of Thailand. Known as the 'River of Kings', this historic waterway has been the lifeblood of Bangkok for centuries. Unicorn Cruise offers the most premium fleet for those seeking an elevated experience. Whether you are looking for a romantic dinner cruise at sunset or a private luxury charter for an exclusive corporate event, our vessels provide the perfect backdrop.",
        "Experience why millions of travelers choose to dine while sailing past the majestic Wat Arun (Temple of Dawn) and the illuminated Grand Palace. Our itineraries are carefully crafted to ensure you see the most iconic landmarks of Bangkok in comfort and style. From gourmet Thai cuisine to international buffets, the dining experience on board Unicorn Cruise is unparalleled, featuring signature dishes like authentic Massaman Curry and fresh giant river prawns.",
        "Unicorn Cruise is Bangkok's premier booking portal for luxury river experiences, offering transparent pricing, easy boarding procedures from major piers like ICONSIAM and Asiatique, and world-class service.",
      ],
    },
    footer: {
      tagline: "Elevating Bangkok's river experiences through luxury, heritage, and culinary excellence.",
      brand: "Bangkok River Cruise Guide",
      copyright: "© 2026 Bangkok River Cruise Guide",
      contact: "Contact us",
      privacy: "Privacy",
      terms: "Terms",
      cookies: " Cookies",
    },
  },
  th: {
    langLabel: "TH",
    nav: {
      home: "หน้าแรก",
      cruises: "เรือให้บริการ",
      piers: "ท่าเรือ",
      practicalInfo: "ข้อมูลที่ควรรู้",
      event: "จัดอีเวนต์บนเรือ",
      about: "เกี่ยวกับเรา",
      community: "รีวิวจากประสบการณ์จริง",
    },
    hero: {
      title: "คู่มือล่องเรือแม่น้ำเจ้าพระยา",
      subtitle: "ดื่มด่ำการเดินทางสุดหรูที่ไม่รู้ลืม ผ่านใจกลางสายน้ำประวัติศาสตร์แห่งกรุงเทพฯ ที่ซึ่งวัฒนธรรมดั้งเดิมบรรจบกับความหรูหราร่วมสมัย",
    },
    landmarks: {
      title: "แลนด์มาร์กริมแม่น้ำเจ้าพระยา",
      subtitle: "แม่น้ำเจ้าพระยาคือเส้นเลือดใหญ่ของกรุงเทพมหานคร ไหลผ่านใจกลางเมืองเก่าย่านรัตนโกสินทร์",
      landmark: "ไอคอนสยาม",
      description: "บรรยากาศน่าประทับใจเป็นพิเศษในยามเย็น เมื่อแสงไฟจากอาคารและเรือที่แล่นผ่านสะท้อนลงบนแม่น้ำเจ้าพระยาอย่างสวยงาม ภายใน นักท่องเที่ยวสามารถเพลิดเพลินไปกับการช้อปปิ้ง รับประทานอาหาร และพักผ่อนอย่างมีชีวิตชีวา ในบรรยากาศที่ทั้งหรูหราและเปี่ยมไปด้วยพลัง",
      cta: "สำรวจเพิ่มเติม",
      items: [
        {
          key: "iconsiam",
          title: "ไอคอนสยาม",
          description: "บรรยากาศน่าประทับใจเป็นพิเศษในยามเย็น เมื่อแสงไฟจากอาคารและเรือที่แล่นผ่านสะท้อนลงบนแม่น้ำเจ้าพระยาอย่างสวยงาม ภายใน นักท่องเที่ยวสามารถเพลิดเพลินไปกับการช้อปปิ้ง รับประทานอาหาร และพักผ่อนอย่างมีชีวิตชีวา ในบรรยากาศที่ทั้งหรูหราและเปี่ยมไปด้วยพลัง",
        },
        {
          key: "rama8",
          title: "สะพานพระราม 8",
          description: "เป็นสะพานขึงแบบอสมมาตรที่ยาวติดอันดับโลก ข้ามแม่น้ำเจ้าพระยาเพื่อเชื่อมฝั่งพระนครกับฝั่งธนบุรี โดดเด่นด้วยเสาสะพานเดี่ยวรูปตัว Y คว่ำ ออกแบบอย่างวิจิตรเพื่อเฉลิมพระเกียรติพระบาทสมเด็จพระบรมชนกาธิเบศร มหาภูมิพลอดุลยเดชมหาราช บรมนาถบพิตร (รัชกาลที่ 8) และช่วยบรรเทาปัญหาการจราจร",
        },
        {
          key: "grandPalace",
          title: "พระบรมมหาราชวัง",
          description: "สัญลักษณ์สำคัญของกรุงเทพฯ และอดีตที่ประทับของพระมหากษัตริย์ไทย โดดเด่นด้วยสถาปัตยกรรมไทยอันประณีตและบรรยากาศสง่างามริมแม่น้ำเจ้าพระยา เป็นหนึ่งในแลนด์มาร์กที่นักท่องเที่ยวไม่ควรพลาดเมื่อมาเยือนกรุงเทพฯ",
        },
        {
          key: "watArun",
          title: "วัดอรุณราชวราราม",
          description: "วัดเก่าแก่ริมแม่น้ำเจ้าพระยาที่มีพระปรางค์สูงโดดเด่น เป็นหนึ่งในวิวที่สวยที่สุดของกรุงเทพฯ โดยเฉพาะช่วงพระอาทิตย์ตกและยามค่ำคืนเมื่อแสงไฟสะท้อนกับแม่น้ำ",
        },
      ],
    },
    operators: {
      title: "ผู้ให้บริการเรือทั้งหมด",
      seeAll: "ดูทั้งหมด",
      categories: ["เรือทั้งหมด", "เรือดินเนอร์", "เรือซันเซ็ต", "เรือหรูสมัยใหม่", "เรือหรูคลาสสิก", "เรือดินเนอร์โรแมนติก"],
      labels: { price: "ราคา", decks: "ชั้น", levels: "2 ชั้น", dinner: "เรือดินเนอร์", rating: "4.7 (1,503 reviews)", foods: ["Buffet", "Fusion set", "Thai set"], cta: "ดูรายละเอียด" },
      cards: [
        { title: "VELA Cruise", price: "฿699-1,600", category: "dinner" },
        { title: "Riverside Faraya Cruise", price: "฿699-1,600", category: "dinner" },
        { title: "White Orchid River Cruise", price: "฿899-1,600", category: "dinner" },
        { title: "Unicorn Cruise", price: "฿1,690-2,200", category: "modern" },
        { title: "Viva Alangka Cruise", price: "฿1,300-1,900", category: "sunset" },
        { title: "Meridian Cruise", price: "฿1,400-2,000", category: "classic" },
        { title: "Royal Romantic Dining", price: "฿1,890-2,500", category: "romantic" },
      ],
    },
    culinary: {
      title: "มื้อพิเศษบนเรือกลางแม่น้ำ",
      subtitle: "เชฟระดับโลกของเราผสานความดั้งเดิมและนวัตกรรมเข้าด้วยกันอย่างลงตัว เพลิดเพลินไปกับเมนูอาหารไทยแท้ๆ และอาหารนานาชาติยอดนิยม ที่คัดสรรมาอย่างดี ปรุงด้วยวัตถุดิบสดใหม่จากท้องถิ่น",
      items: [
        ["มีเมนูมังสวิรัติ", "เมนูมังสวิรัติคุณภาพ พร้อมเสิร์ฟอย่างพิถีพิถัน"],
        ["วัตถุดิบรับรองฮาลาล", "วัตถุดิบฮาลาลได้มาตรฐาน มั่นใจทุกมื้ออาหาร"],
        ["มีเมนูปลอดกลูเตน", "ตัวเลือกเมนูปราศจากกลูเตน เพื่อมื้ออาหารที่ใส่ใจ"],
        ["ล่องเรือพร้อมบุฟเฟต์อาหารอินเดีย", "บุฟเฟต์อินเดียรสต้นตำรับ บนเรือดินเนอร์ครูซสุดหรู"],
      ],
    },
    piers: {
      title: "ท่าเทียบเรือ",
      seeAll: "ดูทั้งหมด",
      hours: "เปิดให้บริการทุกวัน: 06:00-23:00 น.",
      cards: ["ท่าเรือไอคอนสยาม", "ท่าเรือริเวอร์ซิตี้", "ท่าเรือเอเชียทีค", "ท่ามหาราช", "ท่าเรือสาทร", "ท่าเรือยอดพิมาน", "ท่าเรือเทอร์มินอล 21 พระราม 3", "ท่าเรือวัดอรุณ"],
      submenu: ["ICONSIAM Pier", "River City Pier", "Asiatique the Riverfront Pier"],
    },
    blogs: {
      title: "บล็อกประสบการณ์จริง",
      subtitle: "ค้นพบเรื่องราวจากนักเดินทางที่ได้สัมผัสประสบการณ์ล่องเรือของเรา",
      seeAll: "ดูทั้งหมด",
      readMore: "อ่านต่อ...",
      date: "01 ม.ค. 2026",
    },
    reviews: {
      title: "รีวิวจากผู้ใช้งาน",
      subtitle: "รีวิวจริงจากแขกผู้ใช้งานที่ผ่านการยืนยัน",
      seeAll: "ดูทั้งหมด",
      verified: "จากผู้ใช้งานที่ยืนยันแล้ว",
      date: "01 ม.ค. 2026",
    },
    seo: {
      title: "ค้นพบเรือสำราญสุดหรูสายแม่น้ำในกรุงเทพ",
      paragraphs: [
        "การล่องเรือบนแม่น้ำ Chao Phraya เป็นมากกว่าการนั่งเรือธรรมดา หากแต่คือประตูสู่หัวใจและจิตวิญญาณของประเทศไทย ในนามของ 'แม่น้ำแห่งราชา' (River of Kings) สายน้ำประวัติศาสตร์นี้ได้หล่อเลี้ยง Bangkok มายาวนานหลายศตวรรษ Unicorn Cruise ภาคภูมิใจนำเสนอกองเรือระดับพรีเมียมสำหรับผู้แสวงหาประสบการณ์ที่เหนือกว่า ไม่ว่าจะเป็นมื้อค่ำสุดโรแมนติกยามอาทิตย์อัสดง หรือการเช่าเหมาลำสุดหรูสำหรับงานองค์กรระดับ exclusive เรือทุกลำของเราล้วนเป็นฉากหลังอันสมบูรณ์แบบ",
        "สัมผัสเหตุผลที่นักเดินทางหลายล้านคนทั่วโลกเลือกรับประทานมื้อพิเศษพร้อมล่องผ่าน Wat Arun (Temple of Dawn) อันสง่างาม และ Grand Palace ที่ส่องประกายระยิบระยับ ทุกเส้นทางของเราถูกออกแบบมาอย่างพิถีพิถัน เพื่อให้ท่านได้ชมสถานที่สำคัญของ Bangkok ในความสะดวกสบายและสไตล์ ตั้งแต่อาหารไทยรสเลิศไปจนถึงบุฟเฟต์นานาชาติ มื้ออาหารบน Unicorn Cruise คือประสบการณ์ที่หาที่ใดเทียบไม่ได้ พร้อมเมนูซิกเนเจอร์อย่าง Massaman Curry สูตรต้นตำรับและกุ้งแม่น้ำตัวโตสดใหม่",
        "Unicorn Cruise คือพอร์ทัลจองเรือสำราญสายแม่น้ำชั้นนำของ Bangkok นำเสนอราคาที่โปร่งใส ขั้นตอนการขึ้นเรือที่สะดวกจากท่าเรือสำคัญอย่าง ICONSIAM และ Asiatique พร้อมบริการระดับ world-class",
      ],
    },
    footer: {
      tagline: "ยกระดับประสบการณ์การล่องแม่น้ำในกรุงเทพฯ ด้วยความหรูหรา มรดกทางวัฒนธรรม และความเป็นเลิศด้านอาหาร",
      brand: "คู่มือล่องเรือแม่น้ำเจ้าพระยา",
      copyright: "© 2026 Bangkok River Cruise Guide",
      contact: "ติดต่อเรา",
      privacy: "นโยบาย",
      terms: "เงื่อนไข",
      cookies: "คุกกี้",
    },
  },
};
